---
name: trigger build-test-deploy on jenkins for a release tag
on:
  release:
    types: [published, prereleased, released]
jobs:
  trigger:
    name: Trigger build for a release
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "https://jenkins.vizlib.ninja/job/astrato/job/docker/job/build_astrato_images/buildWithParameters?TAG=${{ github.ref_name }}"
          echo "https://jenkins.vizlib.ninja/job/astrato/job/docker/job/build_astrato_images/buildWithParameters?TAG=${{ github.sha }}"
          echo "${{ github.event }}"
