---
name: trigger build-test-deploy on jenkins
on:
  push:
    branches:
      - main
      - 'hotfix/**'
      - master # only here
jobs:
  trigger:
    name: Trigger build
    runs-on: ubuntu-latest
    steps:
      - run: |
          BRANCH=${{ github.ref_name }}
          if [[ "${BRANCH}" == "master" ]]; then
              BRANCH="origin/master"
          fi
          echo "https://jenkins.vizlib.ninja/job/astrato/job/docker/job/build_astrato_images/buildWithParameters?TAG=${BRANCH}"
          echo "https://jenkins.vizlib.ninja/job/astrato/job/docker/job/build_astrato_images/buildWithParameters?TAG=${{ github.sha }}"
