---
name: trigger build-test-deploy on jenkins for a release tag
on:
  release:
    # to run when stable and pre-releases publish - subscribe to published instead of released and prereleased
    types:
      - published

env:
  # renovate: datasource=github-releases depName=hashicorp/terraform
  ENV TF_VERSION: 1.4.3

jobs:
  trigger-release:
    if: "!github.event.release.prerelease"
    name: Trigger build for a release
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "https://jenkins.vizlib.ninja/job/astrato/job/docker/job/build_astrato_images/buildWithParameters?TAG=${{ github.ref_name }}"
          echo "https://jenkins.vizlib.ninja/job/astrato/job/docker/job/build_astrato_images/buildWithParameters?TAG=${{ github.sha }}"
  trigger-prerelease:
    if: "github.event.release.prerelease"
    name: Trigger build for a prerelease
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "https://jenkins.vizlib.ninja/job/astrato/job/docker/job/build_astrato_images/buildWithParameters?TAG=${{ github.ref_name }}"
          echo "https://jenkins.vizlib.ninja/job/astrato/job/docker/job/build_astrato_images/buildWithParameters?TAG=${{ github.sha }}"


      # Security scan terraform code
      - name: Terraform Security
        if: github.event.pull_request.merged != true && github.event.pull_request.state != 'closed' || failure()
        id: security
        uses: bridgecrewio/checkov-action@v12.2340.0
        with:
          directory: ${{ matrix.dir }}
          soft_fail: false
          download_external_modules: true
